apiVersion: v1
kind: Service
metadata:
  name: {{ include "cdc-platform.fullname" . }}-connect
  labels:
    {{- include "cdc-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-connect
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: rest
      protocol: TCP
      name: rest
  selector:
    {{- include "cdc-platform.connectSelectorLabels" . | nindent 4 }}
